security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\Utilisateurs: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateurs
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UsersAuthenticator
      logout:
        path: app_logout
        target: app_connexion
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week
        path: /
        secure: true

  access_control:
    # Public routes
    - { path: ^/connexion$, roles: PUBLIC_ACCESS }

    # Invitation system (admin only)
    - { path: ^/invitation, roles: ROLE_ADMIN }

    # ADMIN exclusive
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/planning/edit, roles: ROLE_ADMIN }
    - { path: ^/formation/dates, roles: ROLE_ADMIN }
    - { path: ^/jour-ferie/sync, roles: ROLE_ADMIN, methods: [POST] }
    - { path: ^/jour-ferie/delete, roles: ROLE_ADMIN }

    # GESTIONNAIRE permissions
    - { path: ^/formation/content, roles: ROLE_GESTIONNAIRE }
    - { path: ^/jour-ferie/local/add, roles: ROLE_GESTIONNAIRE }

    # CONSULTATION access
    - { path: ^/planning, roles: ROLE_CONSULTATION }
    - { path: ^/formation, roles: ROLE_CONSULTATION }
    - { path: ^/jour-ferie, roles: ROLE_CONSULTATION }

    # Shared authenticated routes
    - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }

  role_hierarchy:
    ROLE_ADMIN: ROLE_GESTIONNAIRE
    ROLE_GESTIONNAIRE: ROLE_CONSULTATION
    ROLE_CONSULTATION: ROLE_USER
  




# security:
#   password_hashers:
#     Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
#     App\Entity\Utilisateurs: "auto"

#   providers:
#     app_user_provider:
#       entity:
#         class: App\Entity\Utilisateurs
#         property: email

#   firewalls:
#     dev:
#       pattern: ^/(_(profiler|wdt)|css|images|js)/
#       security: false

#     main:
#       lazy: true
#       provider: app_user_provider
#       custom_authenticator: App\Security\UsersAuthenticator
#       logout:
#         path: app_logout
#         target: app_login
#       remember_me: # Add if needed
#         secret: "%kernel.secret%"
#         lifetime: 604800 # 1 week

#   access_control:
#     - { path: ^/admin, roles: ROLE_ADMIN }
#     - { path: ^/jour/ferie/sync-api, roles: ROLE_ADMIN }
#     - { path: ^/formation, roles: ROLE_GESTIONNAIRE }
#     - { path: ^/invitation, roles: ROLE_ADMIN }
#     - { path: ^/planning/edit, roles: [ROLE_ADMIN, ROLE_GESTIONNAIRE] }
#     - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }

#   role_hierarchy:
#     ROLE_ADMIN: [ROLE_GESTIONNAIRE, ROLE_CONSULTATION]
#     ROLE_GESTIONNAIRE: ROLE_CONSULTATION

